---
title: "Cladophora Microbiota, 2014, 16S Amplicon Analysis"
author: "Michael Braus"
date: "`r Sys.Date()`"
output: html_document
---
```{r global_options, include=FALSE}
knitr::opts_chunk$set(
  fig.width=5, fig.height=3, 
  fig.path='Clado-Analysis-Figs/', 
  warning=FALSE, 
  message=FALSE, 
  cache=TRUE)
setwd("~/Dropbox/clado-manuscript/Mikes_MS_Data/")
```
```{r load_packages, results="hide"}
#source('http://bioconductor.org/biocLite.R')
#biocLite('phyloseq')
library(phyloseq)
library(ggplot2)
library(plyr)
library(dplyr)
library(Rmisc)
library(DESeq2)
library(doParallel)
library(vegan)
library(grid)
library(gridExtra)
```
``` {r load_data, results="hide"}
# Load biom file. 
biom <- import_biom("OTU_table.biom", "~/Dropbox/clado-manuscript/Nephele/PipelineResults_NMEPINZ20QK1/nephele_outputs/tree.tre", parseFunction=parse_taxonomy_greengenes)
biom
```
``` {r merge_metadata}
# Load and merge sample metadata with read data (biom). 
sam.data <- read.csv(file="sample.data.csv", row.names=1, header=TRUE)
sam.data$Date <- as.factor(sam.data$Date)
sam.data$DateSite <- paste(sam.data$Date, sam.data$Site)
sample_data(biom) <- sam.data
sample_data(biom)
```
```{r relabund}
# Normalize by relative abundance. 
biom.relabund <- transform_sample_counts(biom, function(x) x / sum(x))
```
```{r ordination}
# Ordination plot, k = 3. 
ordNMDS.k3 <- ordinate(biom.relabund, method="NMDS", distance="bray", k=3)
```
```{r plot_ordination}
ord.k3 <- plot_ordination(biom.relabund, ordNMDS.k3, shape="Site", color = "Date") + geom_point(size=2)
ord.k3 + labs(title = "Cladophora, 2014") + theme_bw() + scale_colour_hue(h=c(300, 500))
```
```{r adonis}
df = as(sample_data(biom), "data.frame")
d = phyloseq::distance(biom, "bray")
clado.adonis = adonis(d ~ Date*Site, df)
clado.adonis
```
```{r est_richness}
biom.rich.est <- estimate_richness(biom, measures = NULL)
biom.rich.est$SampleID.1 <- row.names(biom.rich.est)
biom.rich.est <- merge(biom.rich.est, sam.data, by = "SampleID.1")
biom.rich.est$Date <- as.character(biom.rich.est$Date)
biom.rich.est$Date <- as.numeric(biom.rich.est$Date)
head(biom.rich.est)
```
```{r plot_richness_obs}
# Plot observed richness. 
biom.rich.est.obs <- summarySE(biom.rich.est, measurevar="Observed", groupvars=c("Date","Site"))
p.obs <- ggplot(biom.rich.est.obs, aes(x=Date, y=Observed, color = Site)) + geom_point() +  geom_errorbar(aes(ymin=Observed-se, ymax=Observed+se)) + geom_line() + scale_colour_hue(h=c(400, 120))
p.obs + theme_bw() + theme(axis.text.x = element_text(size = 10, angle = 45, hjust=1),axis.text.y = element_text(size = 10))
```
```{r plot_richness_sha}
# Plot Shanon index richness. 
biom.rich.est.sha <- summarySE(biom.rich.est, measurevar="Shannon", groupvars=c("Date","Site"))
p.sha <- ggplot(biom.rich.est.sha, aes(x=Date, y=Shannon, color = Site)) + geom_point() +  geom_errorbar(aes(ymin=Shannon-se, ymax=Shannon+se)) + geom_line() + scale_colour_hue(h=c(400, 120))
p.sha + theme_bw() + theme(axis.text.x = element_text(size = 10, angle = 45, hjust=1),axis.text.y = element_text(size = 10))
```
```{r top30_genera, fig.height=15, fig.width=8}
# Find top 30 genera and subset biom.relabund. 
sort.genera <- sort(tapply(taxa_sums(biom.relabund), tax_table(biom.relabund)[, "Genus"], sum), TRUE)
top.genera <- sort.genera[1:30]
top.genera.list <- names(top.genera)
biom.relabund.subset = subset_taxa(biom.relabund, Genus %in% top.genera.list)
biom.relabund.subset.taxa <- subset_taxa(biom.relabund.subset, Genus %in% as.factor(top.genera.list))
biom.relabund.subset.taxa
relabund.top.genera <- psmelt(biom.relabund.subset.taxa)
relabund.top.genera.genus <- relabund.top.genera%>%
  group_by(Sample, Genus)%>%
  mutate(GenusAbundance = sum(Abundance))%>%
  distinct(Sample, GenusAbundance, TreatmentGroup, Site, Date, Family, Genus)
head(relabund.top.genera.genus)
```
```{r est_top30_genera}
# Summary of genus abundance of top 30 genera. 
relabund.top.genera.genus.est <- summarySE(relabund.top.genera.genus, measurevar="GenusAbundance", groupvars=c("Site","Date", "Genus"))
head(relabund.top.genera.genus.est)
relabund.top.genera.genus.est$Date <- as.character(relabund.top.genera.genus.est$Date)
relabund.top.genera.genus.est$Date <- as.numeric(relabund.top.genera.genus.est$Date)
```
```{r plot_top30_genera, fig.height=20, fig.width=8}
# Plot summary of genus abundance of top 30 genera. 
p <- ggplot(relabund.top.genera.genus.est, aes(x=Date, y=GenusAbundance, color = Site)) + geom_point() +  geom_errorbar(aes(ymin=GenusAbundance-se, ymax=GenusAbundance+se)) +  geom_line() + facet_wrap(~Genus, ncol = 3, scales="free_y") + scale_colour_hue(h=c(400, 120))
p + theme_bw() + theme(axis.text.x = element_text(size = 10, angle = 45, hjust=1),axis.text.y = element_text(size = 10))
```
```{r est_methanos}
# Find methanotrophic bacteria by genus. 
methanolist <- read.table(file = "taxa-of-interest/methanos.txt")
methanolist <- as.vector(methanolist$V1)
biom.relabund.methanos <- subset_taxa(biom.relabund, Genus %in% as.factor(methanolist))
biom.relabund.methanos
relabund.methanos <- psmelt(biom.relabund.methanos)
relabund.methanos.genus <- relabund.methanos%>%
  group_by(Sample, Genus)%>%
  mutate(GenusAbundance = sum(Abundance))%>%
  distinct(Sample, GenusAbundance, TreatmentGroup, Site, Date, Family, Genus)
relabund.methanos.genus.est <- summarySE(relabund.methanos.genus, measurevar="GenusAbundance", groupvars=c("Site","Date", "Genus"))
head(relabund.methanos.genus.est)
relabund.methanos.genus.est$Date <- as.character(relabund.methanos.genus.est$Date)
relabund.methanos.genus.est$Date <- as.numeric(relabund.methanos.genus.est$Date)
```
```{r plot_methanos, fig.width=8, fig.height=4}
# Plot summary of genus abundance of methanotrophic genera. 
p <- ggplot(relabund.methanos.genus.est, aes(x=Date, y=GenusAbundance, color = Site)) + geom_point() +  geom_errorbar(aes(ymin=GenusAbundance-se, ymax=GenusAbundance+se)) +  geom_line() + facet_wrap(~Genus, ncol = 3, scales="free_y") + scale_colour_hue(h=c(400, 120))
p + theme_bw() + theme(axis.text.x = element_text(size = 10, angle = 45, hjust=1),axis.text.y = element_text(size = 10))
```
```{r all_genera}
# Find all genera
all.genera <- sort(get_taxa_unique(biom.relabund, "Genus"), decreasing=FALSE)
biom.relabund.all.genera <- subset_taxa(biom.relabund, Genus %in% as.factor(all.genera))
biom.relabund.all.genera <- psmelt(biom.relabund.all.genera)
biom.relabund.all.genera.genus <- biom.relabund.all.genera%>%
  group_by(Sample, Genus)%>%
  mutate(GenusAbundance = sum(Abundance))%>%
  distinct(Sample, GenusAbundance, TreatmentGroup, Site, Date, Family, Genus)
```
```{r plot_all_genera, fig.height=150, fig.width=8}
biom.relabund.all.genera.genus.est <- summarySE(biom.relabund.all.genera.genus, measurevar="GenusAbundance", groupvars=c("Site","Date", "Genus"))
head(biom.relabund.all.genera.genus.est)
biom.relabund.all.genera.genus.est$Date <- as.character(biom.relabund.all.genera.genus.est$Date)
biom.relabund.all.genera.genus.est$Date <- as.numeric(biom.relabund.all.genera.genus.est$Date)
p <- ggplot(biom.relabund.all.genera.genus.est, aes(x=Date, y=GenusAbundance, color = Site)) + geom_point() +  geom_errorbar(aes(ymin=GenusAbundance-se, ymax=GenusAbundance+se)) +  geom_line() + facet_wrap(~Genus, ncol = 3, scales="free_y") + scale_colour_hue(h=c(400, 120))
p + theme_bw() + theme(axis.text.x = element_text(size = 10, angle = 45, hjust=1),axis.text.y = element_text(size = 10))
```
```{r phyla_abundance}
# We want to calculate the total relative abundance of each phylum. 
# "melt" the phyloseq data into a dataframe and then take the top X most abundant phyla. 
biom.melt <- psmelt(biom)
biom.melt.sorted <- biom.melt %>%
  group_by(Sample,Phylum) %>%
  summarize(PhyAbund = sum(Abundance))%>%
  group_by(Phylum)%>%
  summarize(MeanPhyAbund = mean(PhyAbund))%>%
  arrange(-MeanPhyAbund)
```
```{r top_phyla_abundance}
# List of nPhyla top most abundant phyla. 
nPhyla = 13
PhylumList <- biom.melt.sorted[1:nPhyla,1]
PhylumList <- PhylumList[is.na(PhylumList)==FALSE,]
PhylumList <- levels(droplevels(as.factor(PhylumList$Phylum)))
PhylumList
# Subset biom.melt for phyla. 
biom.subset <- subset_taxa(biom, Phylum %in% PhylumList)
biom.subset.melt <- psmelt(biom.subset)
biom.subset.melt.sorted = biom.subset.melt %>%
  group_by(Sample,Site,Date,Phylum) %>%
  summarize(PhyAbund = sum(Abundance))
```
```{r est_phylum_abundance}
# Summarize phylum abundances. 
biom.subset.melt.sorted.est <- summarySE(biom.subset.melt.sorted, measurevar="PhyAbund", groupvars=c("Site","Date", "Phylum"))
head(biom.subset.melt.sorted.est)
biom.subset.melt.sorted.est$Date <- as.character(biom.subset.melt.sorted.est$Date)
biom.subset.melt.sorted.est$Date <- as.numeric(biom.subset.melt.sorted.est$Date)
```
```{r plot_phylum_abundance_est, fig.width=8, fig.height=8}
# Plot top phyla abundances. 
p <- ggplot(biom.subset.melt.sorted.est, aes(x=Date, y=PhyAbund, color = Site)) + geom_point() +  geom_errorbar(aes(ymin=PhyAbund-se, ymax=PhyAbund+se)) +  geom_line() + facet_wrap(~Phylum, ncol = 3, scales="free_y") + scale_colour_hue(h=c(400, 120))
p + theme_bw() + theme(axis.text.x = element_text(size = 10, angle = 45, hjust=1),axis.text.y = element_text(size = 10)) + labs(x="Amendment",y="Relative abundance")
```
```{r top30_classes}
# Find top 30 classes and subset biom.relabund. 
sort.classes <- sort(tapply(taxa_sums(biom.relabund), tax_table(biom.relabund)[, "Class"], sum), TRUE)
top.classes <- sort.classes[1:30]
top.classes.list <- names(top.classes)
biom.relabund.subset = subset_taxa(biom.relabund, Class %in% top.classes.list)
biom.relabund.subset.taxa <- subset_taxa(biom.relabund.subset, Class %in% as.factor(top.classes.list))
biom.relabund.subset.taxa
relabund.top.classes <- psmelt(biom.relabund.subset.taxa)
relabund.top.classes.class <- relabund.top.classes%>%
  group_by(Sample, Class)%>%
  mutate(ClassAbundance = sum(Abundance))%>%
  distinct(Sample, ClassAbundance, TreatmentGroup, Site, Date, Family, Class)
relabund.top.classes.class.print <- summarySE(relabund.top.classes.class, measurevar="ClassAbundance", groupvars=c("Class"))
relabund.top.classes.class.print[,c("Class","N","ClassAbundance")]
```
```{r est_top30_classes}
# Summary of class abundance of top 30 classes. 
relabund.top.classes.class.est <- summarySE(relabund.top.classes.class, measurevar="ClassAbundance", groupvars=c("Site","Date", "Class"))
head(relabund.top.classes.class.est)
relabund.top.classes.class.est$Date <- as.character(relabund.top.classes.class.est$Date)
relabund.top.classes.class.est$Date <- as.numeric(relabund.top.classes.class.est$Date)
```
```{r plot_top30_classes, fig.height=20, fig.width=8}
# Plot summary of class abundance of top 30 classes. 
p <- ggplot(relabund.top.classes.class.est, aes(x=Date, y=ClassAbundance, color = Site)) + geom_point() +  geom_errorbar(aes(ymin=ClassAbundance-se, ymax=ClassAbundance+se)) +  geom_line() + facet_wrap(~Class, ncol = 3, scales="free_y") + scale_colour_hue(h=c(400, 120))
p + theme_bw() + theme(axis.text.x = element_text(size = 10, angle = 45, hjust=1),axis.text.y = element_text(size = 10))
```
```{r all_classes}
# Find all classes
all.classes <- sort(get_taxa_unique(biom.relabund, "Class"), decreasing=FALSE)
biom.relabund.all.classes <- subset_taxa(biom.relabund, Class %in% as.factor(all.classes))
biom.relabund.all.classes <- psmelt(biom.relabund.all.classes)
biom.relabund.all.classes.class <- biom.relabund.all.classes%>%
  group_by(Sample, Class)%>%
  mutate(ClassAbundance = sum(Abundance))%>%
  distinct(Sample, ClassAbundance, TreatmentGroup, Site, Date, Family, Class)
```
```{r est_all_classes}
biom.relabund.all.classes.class.est <- summarySE(biom.relabund.all.classes.class, measurevar="ClassAbundance", groupvars=c("Site","Date", "Class"))
head(biom.relabund.all.classes.class.est)
biom.relabund.all.classes.class.est$Date <- as.character(biom.relabund.all.classes.class.est$Date)
biom.relabund.all.classes.class.est$Date <- as.numeric(biom.relabund.all.classes.class.est$Date)
```
```{r plot_all_classes, fig.height=50, fig.width=8}
p <- ggplot(biom.relabund.all.classes.class.est, aes(x=Date, y=ClassAbundance, color = Site)) + geom_point() +  geom_errorbar(aes(ymin=ClassAbundance-se, ymax=ClassAbundance+se)) +  geom_line() + facet_wrap(~Class, ncol = 3, scales="free_y") + scale_colour_hue(h=c(400, 120))
p + theme_bw() + theme(axis.text.x = element_text(size = 10, angle = 45, hjust=1),axis.text.y = element_text(size = 10))
```
```{r load_mendota_lter_data}
# Data downloaded from 
data <- read.csv("north_temperate_lakes_lter__daily_water_temperature_-_lake_mendota.csv", header=T)
head(data)
nolegend <- theme(legend.position="none")
Jdays <- c(172,178,185,199,206,214)
```
```{r subet_wtemp_depth}
# Subset all wtemp at or below 1.5 meters (sample depth up to shore). 
clado.depth <- subset(data, depth<=1.5, select = year4:wtemp)
```
```{r plot_wtemp_all_years}
# All years (2006-2016), full year. 
p <- qplot(clado.depth$daynum, y = clado.depth$wtemp)
p <- p + geom_point(aes(colour = clado.depth$year4), size=1, alpha = 0.8) + 
  scale_y_continuous(limits = c(4,30))+
  labs(title = "Water Temperature <1.5m Depth, Lake Mendota") + 
  xlab("Julian Day") + ylab("Temperature °C")+ 
  geom_vline(xintercept=Jdays, colour="darkgreen", linetype = "longdash") +
  guides(color=guide_legend(title="Year")) + 
  scale_colour_gradient(low = "darkred")
p+ theme_bw() + theme(axis.text.x = element_text(size = 10, angle = 45, hjust=1),axis.text.y = element_text(size = 10))
```
```{r plot_wtemp_all_years_zoom}
# All years (2006-2016), sample dates ± 25 days
clado.depth.zoom <- subset(clado.depth, daynum>=150 & daynum<=250, select = year4:wtemp)
p <- qplot(clado.depth.zoom$daynum, y = clado.depth.zoom$wtemp) + 
  scale_y_continuous(limits = c(10,30))+
  geom_point(aes(colour = clado.depth.zoom$year4), size=1, alpha = 0.8) + 
  labs(title = "Water Temperature <1.5m Depth, Lake Mendota", x="Julian Day", y="Temperature °C") + 
  geom_vline(xintercept=Jdays, colour="darkgreen", linetype = "longdash") + 
  guides(color=guide_legend(title="Year")) + scale_colour_gradient(low = "darkred")
p+ theme_bw() + theme(axis.text.x = element_text(size = 10, angle = 45, hjust=1),axis.text.y = element_text(size = 10))
```
```{r plot_wtemp_all_years_facet, fig.width=5, fig.height=6,}
# Smarter way to make grid of plots. 
p <- ggplot(clado.depth.zoom, aes(daynum, wtemp))
p <- p + geom_point(size = 0.5) + 
  ylim(15,30) + 
  facet_wrap(~year4, ncol = 3) + 
  geom_vline(xintercept=Jdays, colour="grey30", linetype = "longdash") +
  guides(color=guide_legend(title="Year")) +
  labs(title = "Water Temperature <1.5m Depth, Lake Mendota", x="Julian Day", y="Temperature °C")
p + theme_bw() + theme(axis.text.x = element_text(size = 10, angle = 45, hjust=1),axis.text.y = element_text(size = 10))
```
```{r genera_of_interest}
# Find genera of interest and subset biom.relabund. 
genofint <- read.table(file = "taxa-of-interest/genera-of-interest.txt")
genofint.list <- as.vector(genofint$V1)
biom.relabund.subset.genofint = subset_taxa(biom.relabund, Genus %in% genofint.list)
biom.relabund.subset.genofint.taxa <- subset_taxa(biom.relabund.subset.genofint, Genus %in% as.factor(genofint.list))
biom.relabund.subset.genofint.taxa
relabund.genofint <- psmelt(biom.relabund.subset.genofint.taxa)
relabund.genofint.genus <- relabund.genofint%>%
  group_by(Sample, Genus)%>%
  mutate(GenusAbundance = sum(Abundance))%>%
  distinct(Sample, GenusAbundance, TreatmentGroup, Site, Date, Family, Genus)
head(relabund.genofint.genus)
```
```{r est_genera_of_interest}
# Summary of genus abundance of genera of interest. 
relabund.genofint.genus.est <- summarySE(relabund.genofint.genus, measurevar="GenusAbundance", groupvars=c("Site","Date", "Genus"))
head(relabund.genofint.genus.est)
relabund.genofint.genus.est$Date <- as.character(relabund.genofint.genus.est$Date)
relabund.genofint.genus.est$Date <- as.numeric(relabund.genofint.genus.est$Date)
```
```{r plot_genera_of_interest, fig.width=4.5, fig.height=9}
# Plot summary of genus abundance of genera of interest. 
p <- ggplot(relabund.genofint.genus.est, aes(x=Date, y=GenusAbundance, color = Site)) + geom_point() +  geom_errorbar(aes(ymin=GenusAbundance-se, ymax=GenusAbundance+se)) +  geom_line() + facet_wrap(~Genus, ncol = 2, scales="free_y") + scale_colour_hue(h=c(400, 120))
p + theme_bw() + theme(axis.text.x = element_text(size = 10, angle = 45, hjust=1),axis.text.y = element_text(size = 10))
```
```{r classes_zulk_of_interest}
# Find classes_zulk of interest and subset biom.relabund. 
classzulk <- read.csv(file ="taxa-of-interest/classes-zulkifly.txt", header = T)
classzulk.list <- as.vector(classzulk$Class)
biom.relabund.subset.classzulk = subset_taxa(biom.relabund, Class %in% classzulk.list)
biom.relabund.subset.classzulk.taxa <- subset_taxa(biom.relabund.subset.classzulk, Class %in% as.factor(classzulk.list))
biom.relabund.subset.classzulk.taxa
relabund.classzulk <- psmelt(biom.relabund.subset.classzulk.taxa)
relabund.classzulk.class <- relabund.classzulk%>%
  group_by(Sample, Class)%>%
  mutate(ClassAbundance = sum(Abundance))%>%
  distinct(Sample, ClassAbundance, TreatmentGroup, Site, Date, Family, Class)
head(relabund.classzulk.class)
```
```{r est_classes_zulk_of_interest}
# Summary of class abundance of classes_zulk of interest. 
relabund.classzulk.class.est <- summarySE(relabund.classzulk.class, measurevar="ClassAbundance", groupvars=c("Site","Date","Class"))
head(relabund.classzulk.class.est)
relabund.classzulk.class.est$Date <- as.character(relabund.classzulk.class.est$Date)
relabund.classzulk.class.est$Date <- as.numeric(relabund.classzulk.class.est$Date)
```
```{r plot_classes_zulk_of_interest_merged, fig.width=6.5, fig.height=6}
# Plot MERGED summary of class abundance of classes_zulk of interest and Zulkifly et al. class abundances. 
relabund.classzulk.class.est.merge <- merge(relabund.classzulk.class.est, classzulk, by ="Class")
p <- ggplot(relabund.classzulk.class.est.merge, aes(x=Date, y=ClassAbundance, color = Site)) + geom_point() +  geom_errorbar(aes(ymin=ClassAbundance-se, ymax=ClassAbundance+se)) +  geom_line() + facet_wrap(~Class, ncol = 3, scales="free_y") + scale_colour_hue(h=c(400, 120)) + geom_hline(aes(yintercept = ClassAbundance_zulkifly), linetype="dashed")+ scale_colour_hue(h=c(400, 120))
p + theme_bw() + theme(axis.text.x = element_text(size = 10, angle = 45, hjust=1),axis.text.y = element_text(size = 10))
```