---
title: "Differntial Abundance of Cladophora Microbiota, 2014"
author: "UW"
date: "`r Sys.Date()`"
output: html_document
---
```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=8, fig.height=6, fig.path='Differential_Abundance-figs/', warning=FALSE, message=FALSE, cache=TRUE)
```
```{r load_packages, results="hide"}
setwd("~/Dropbox/clado-manuscript/Mikes_MS_Data/")
#source('http://bioconductor.org/biocLite.R')
#biocLite('phyloseq')
library(phyloseq)
library(ggplot2)
library(plyr)
library(dplyr)
library(Rmisc)
library(DESeq2)
library(doParallel)
```
``` {r load_data, results="hide"}
# Load biom file. 
biom <- import_biom("OTU_table.biom", "~/Dropbox/clado-manuscript/Nephele/PipelineResults_NMEPINZ20QK1/nephele_outputs/tree.tre", parseFunction=parse_taxonomy_greengenes)
```
``` {r merge_metadata}
sam.data <- read.csv(file="sample.data.csv", row.names=1, header=TRUE)
head(sam.data)
sam.data$Date <- as.factor(sam.data$Date)
sam.data$DateSite <- paste(sam.data$Date, sam.data$Site)
head(sam.data); str(sam.data)
sample_data(biom) <- sam.data
biom; sample_data(biom)
head(otu_table(biom))
```
``` {r sample_summary_etc}
sample.summary <- data.frame(sample_data(biom)) %>%
    group_by(Site,Date) %>%
    summarize(total=n())
sample.summary
# Takes the sample data we just connected to the phyloseq file, in the form of a dataframe,
# Groups it by each combination of sample site and date
# reports the total number of samples we have for each site/date combo - we have 2-3 samples for each.
variables <- expand.grid(Site=c("North","South"),Date=c("172","178","185","199","206","214"))
variables
# Creating a matrix with the different combinations of variables for Site and date
```
```{r make_Dif_Abund}
# We are creating a function called Dif_Abund that will run deseq on each subset of factors (day and Site), 
# and return the factors, OTU ID, base mean, log2-fold change, the SE, and the p value associated with the response.
# This is testing for the question, on each date, are there differences between sample sites?
Dif_Abund = function(Site,Date){
  biom.pruned = prune_samples(sample_data(biom)$Date == paste(Date),biom)
  biom.pruned = prune_samples((sample_data(biom.pruned)$Site == paste(Site) | sample_data(biom.pruned)$Site == "Point"),biom.pruned)
  # Pulling out the samples we want to compare - we will run DESeq for each date. So, we pull out the rows from the site we are interested in,
  # and then also the baseline location (North) for that day, from our biom object.
  biom.pruned = prune_taxa(taxa_sums(biom.pruned) > 0, biom.pruned)
  # Cutting out any OTUs that don't show up in this comparison
  taxonomy <- data.frame(tax_table(biom.pruned))
  # Storing the taxonomy data
  dseq = phyloseq_to_deseq2(biom.pruned, ~Site)
  # Creating the dseq file, and using the formula that tells it we are interested in Site as a factor, and date as the baseline.
  dseq$Site = relevel(dseq$Site,"Point")
  # Establishing that the baseline comparison is for the first day.
  dseq = DESeq(dseq, quiet = TRUE, fitType = "local")
  # Running the actual DESeq function
  results = results(dseq, cooksCutoff=TRUE)
  # Reporting the results from the dseq object we just created
  # You can change Cooks Cutoff to control outliers (TRUE) or not (FALSE)
  results$Date = Date
  results$Site = Site
  # Creates a column in the results dataframe listing the Site
  results = data.frame(results$Site,results$Date,rownames(results),results$baseMean,results$log2FoldChange,results$lfcSE,results$pvalue,taxonomy[,1:7])
  # Pulling out all the results we are actually interested in
  colnames(results) = c("Site","Date","OTU","baseMean","l2FC","SE","pvalue","Kingdom","Phylum","Class","Order","Family","Genus","Species")
  # Naming the columns appropriately
  results
  # Return the final results dataframe
}
```
```{r da}
DA <- mdply(variables, Dif_Abund)
# Runs the  differential abundance function we created above on all the combinations of variables
# We are leaving out the first variable, because that is the comparison baseline.
# The formula, as written above, will not tell us if the sites are different from one to the next
# It is looking for OTUs that are increased in relative abundance (compared to the first sampling day)
# across all sites, but accounting for the fact that the sites have different baselines, basically.
```
```{r threshold_fnxn}
threshold = function (thresh){
  filter(DA, baseMean >= thresh) %>% 
    mutate(padj = p.adjust(pvalue,"BH")) %>%
    summarize(cutoff=thresh, count=sum(padj<=0.10, na.rm = TRUE))
}
# Creates a function called "threshold" that will take our DA table as created above, then filter it so that we only keep
# rows where the baseMean (roughly the relative abundance for that OTU) is greater than some threshold, "thresh"
# Then, for those remaining rows, we run a Benjamini-Hochberg correction on our p-values, outputting these adjusted
# values in a new colum ("padj")
# Finally, we report back the threshold, and then the sum of taxa for which we have adjusted p values
# less than or equal to 0.10, our chosen false discovery rate
```
```{r thresh.s}
range = seq(0,3,0.25)
# Creates a sequence of numbers we are interested in for adjusted p values (from 0-3 by 0.25 increments)
thresh.s <- ldply(range, threshold)
# Applys the Threshold function we created above to the range of numbers we created above.
plot(thresh.s$count~thresh.s$cutoff)
# We can plot the threshold for base Mean value against the number of samples that will pass under this cutoff.
# We can see the optimum value to use here (here, 1.5)
```
```{r twelve_fc}
l2fc <- group_by(DA, Site, Date) %>%
  filter(baseMean>=1.5) %>% 
  mutate(padj = p.adjust(pvalue,"BH"))
# We take that differential abundance table we created above ("DA"), and take the sum of the baseMean for each date
# Then we filter the whole set of values to include only those OTUs for which their baseMean was >1.5,
# We then adjust the p values only for those that we expect might be significant.
# I.e., those of very low relative abundance in the first place are not getting assessed at all,
# Allowing us to not test their significance - so untestested values will have NA in the padj column.
dim(l2fc[is.na(l2fc$padj)==TRUE,])[1]/dim(l2fc[])[1]
# Fraction of OTUs that were not tested for significance (padj is "NA")
# We didn't actually cut it down that much, but it might help.
```
```{r cutoff}
cutoff = 1
FDR = 0.1
d = l2fc %>%
  group_by(Site,Date)%>%
  mutate(Sig = ifelse(padj<FDR&l2FC>=cutoff,1,0))%>%
  mutate(Sig = ifelse(is.na(padj)==TRUE,0,Sig))%>%
  group_by(Site,Date)%>%
  count(Site,Date,Sig)%>%
  group_by(Site,Date)%>%
  mutate(Fraction=n/sum(n))
d
# Creates a little table showing which fraction of OTUs were designated as significant or not on each date
# A good number are - 10-30%
```
```{r logfold_change}
FDR = 0.1
d = l2fc
d = group_by(d, Site,Date) %>%
  mutate(sig = ifelse(padj<FDR,1,0))%>%
  mutate(Total=sum(baseMean)) %>%
  mutate(relabund=baseMean/Total)%>%
  filter(padj != 'NA')
# Creates a column designating whether (1) or not (0) the padj is lower than our false discovery rate (set above)
# We also calculate a new relative abundance value using the average across samples
# and we cut out those rows with no p-values
PhylumFraction = 0.005
OTUFraction = 0.001
PhylumList = d %>%
  group_by(Phylum,Date)%>%
  filter(sum(relabund)>=PhylumFraction | relabund>=OTUFraction)
PhylumList = levels(droplevels(PhylumList$Phylum))
# Looks at each phylum, on each date, and sees if the total abundance of OTUs within that phylum is
# greater than the cutoff (PhylumFraction, defined above), OR if the single OTU makes up a large enough fraciton
# of the total community on its own (OTUFraction, defined above)
# Thus, we have selected the phyla we want to plot.
d = filter(d, Phylum %in% PhylumList)
max.l2FC = ddply(d, .(Phylum), summarize, M = max(l2FC))
d$Phylum = factor(d$Phylum, max.l2FC[order(-max.l2FC$M),]$Phylum)
# makes a dataframe with the maximum value of log2Fold change for each phylum
# takes our phylum column, and arranges it in order of our log2FoldChange values
d$sig = as.factor(d$sig)
d.yes = d[d$sig==1,]
d.no = d[d$sig==0,]
# Creates new columns (true/false) for whether it is significant or not
```
```{r plot_logfold_change, fig.height=20}
p = ggplot(d)
p = p + geom_point(data=d.yes, aes(x = Phylum, y = l2FC, fill = Phylum, size=relabund), shape = 21, alpha=0.4, position = position_jitter(w = 0.20))
# p = p + geom_point(data=d.no, aes(x = Date, y = l2FC, fill = sig, size=relabund), shape = 21, alpha=0.3, position = position_jitter(w = 0.20))
# Plotting the significant and the nonsignificant points differently
# size is proportional to relative abundance, and we colour it by Class
p = p + scale_size_continuous("log(Relative\nAbundance)",trans="log",guide="none")
# Transforming the size of the points so it's better visualized
p = p + facet_grid(Date~Site, scales="free_x")
# Saying we want it to present the data separately for each phylum
p = p + geom_hline(yintercept = 1, linetype=2)
p = p + geom_hline(yintercept = -1, linetype=2)
p = p + geom_hline(yintercept = 3.3219, linetype=3)
p = p + geom_hline(yintercept = -3.3219, linetype=3)
p = p + geom_hline(yintercept = 0.0, linetype=1)
# Puts in horizontal lines at reference values
p = p + theme_bw()
# Sets a theme
p = p + theme(strip.text.x = element_text(size = 16), strip.text.y = element_text(size = 16), axis.text.x = element_text(size = 14, angle = 45, hjust = 1, vjust = 1, face="italic"), axis.title.x = element_text(size = 18), axis.text.y = element_text(size=16), axis.title.y = element_text(size = 18), legend.title = element_text(size=18), legend.text = element_text(size = 14), strip.background = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank())
# sets a bunch of visual paramters for the legend (none) and other text
p = p + labs(y = expression(paste("", log[2]," fold change vs. Point site",sep="")))
# sets the label for the y axes.
p
```
```{r plot_logfold_change_proteobac, fig.height=20}
dProteo = d %>%
  filter(Phylum=="Proteobacteria")
d.yesProteo = d.yes %>%
  filter(Phylum=="Proteobacteria")
d.noProteo = d.no %>%
  filter(Phylum=="Proteobacteria")
# Subsetting our data for Proteos
p = ggplot(dProteo)
p = p + geom_point(data=d.yesProteo, aes(x = Order, y = l2FC, fill = Order, size=relabund), shape = 21, alpha=0.4, position = position_jitter(w = 0.20))
# p = p + geom_point(data=d.noProteo, aes(x = Date, y = l2FC, fill = sig, size=relabund), shape = 21, alpha=0.3, position = position_jitter(w = 0.20))
# Plotting the significant and the nonsignificant points differently
# size is proportional to relative abundance, and we colour it by Class
p = p + scale_size_continuous("log(Relative\nAbundance)",trans="log",guide="none")
# Transforming the size of the points so it's better visualized
p = p + facet_grid(Date~Site~Class, scales="free_x")
# Saying we want it to present the data separately for each phylum
p = p + geom_hline(yintercept = 1, linetype=2)
p = p + geom_hline(yintercept = -1, linetype=2)
p = p + geom_hline(yintercept = 3.3219, linetype=3)
p = p + geom_hline(yintercept = -3.3219, linetype=3)
p = p + geom_hline(yintercept = 0.0, linetype=1)
# Puts in horizontal lines at reference values
p = p + theme_bw()
p = p + theme(strip.text.x = element_text(size = 16),
              strip.text.y = element_text(size = 16),
              axis.text.x = element_text(size = 14, angle = 45, hjust = 1, vjust = 1, face="italic"),
              axis.title.x = element_text(size = 18),
              axis.text.y = element_text(size=16),
              axis.title.y = element_text(size = 18),
              legend.title = element_text(size=18),
              legend.text = element_text(size = 14),
              #legend.position = "none",
              strip.background = element_blank(),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank())
# sets a bunch of visual paramters for the legend (none) and other text
p = p + labs(y = expression(paste("", log[2]," fold change vs. Point site",sep="")))
# sets the label for the y axes.
p + theme(legend.position="none")
```
```{r plot_logfold_change_bacteriodetes, fig.height=20}
dBacter = d %>%
  filter(Phylum=="Bacteroidetes")
d.yesBacter = d.yes %>%
  filter(Phylum=="Bacteroidetes")
d.noBacter = d.no %>%
  filter(Phylum=="Bacteroidetes")
p = ggplot(dBacter)
p = p + geom_point(data=d.yesBacter, aes(x = Class, y = l2FC, fill = Class, size=relabund), shape = 21, alpha=0.4, position = position_jitter(w = 0.20))
#p = p + geom_point(data=d.noBacter, aes(x = Class, y = l2FC, fill = Class, size=relabund), shape = 21, alpha=0.3, position = position_jitter(w = 0.20))
# Plotting the significant and the nonsignificant points differently
# size is proportional to relative abundance, and we colour it by Class
p = p + scale_size_continuous("log(Relative\nAbundance)",trans="log",guide="none")
# Transforming the size of the points so it's better visualized
p = p + facet_grid(Date~Site, scales="free_x")
# Saying we want it to present the data separately for each phylum
p = p + geom_hline(yintercept = 1, linetype=2)
p = p + geom_hline(yintercept = -1, linetype=2)
p = p + geom_hline(yintercept = 3.3219, linetype=3)
p = p + geom_hline(yintercept = -3.3219, linetype=3)
p = p + geom_hline(yintercept = 0.0, linetype=1)
# Puts in horizontal lines at reference values
p = p + theme_bw()
# Sets a theme
p = p + theme(strip.text.x = element_text(size = 16),
              strip.text.y = element_text(size = 16),
              axis.text.x = element_text(size = 14, angle = 45, hjust = 1, vjust = 1, face="italic"),
              axis.title.x = element_text(size = 18),
              axis.text.y = element_text(size=16),
              axis.title.y = element_text(size = 18),
              legend.title = element_text(size=18),
              legend.text = element_text(size = 14),
              #legend.position = "none",
              strip.background = element_blank(),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank())
# sets a bunch of visual paramters for the legend (none) and other text
p = p + labs(y = expression(paste("", log[2]," fold change vs. Point site",sep="")))
# sets the label for the y axes.
p + theme(legend.position="none")
```
```{r methanotrophs}
# Find methanotrophs
methanolist <- read.table(file = "methanos.txt")
methanolist <- as.vector(methanolist$V1)
# Create a list of all the possible methanotroph genera
df = l2fc %>%
  filter(Genus %in% as.factor(methanolist))
# Take out only the methanotrophs
df = group_by(df, Site,Date) %>%
  mutate(sig = ifelse(padj<FDR,1,0))%>%
  mutate(Total=sum(baseMean)) %>%
  mutate(relabund=baseMean/Total)%>%
  filter(padj != 'NA')
# Creates a column designating whether (1) or not (0) the padj is lower than our false discovery rate (set above)
# We also calculate a new relative abundance value using the average across samples
# and we cut out those rows with no p-values
df$sig = as.factor(df$sig)
df.yes = df[df$sig==1,]
df.no = df[df$sig==0,]
# Creates new columns (true/false) for whether it is significant or not
p = ggplot(df)
p = p + geom_point(data=df.yes, aes(x = Date, y = l2FC, fill = Site, size=relabund), shape = 21, alpha=0.4, position = position_jitter(w = 0.20))
p = p + geom_point(data=df.no, aes(x = Date, y = l2FC, fill = sig, size=relabund), shape = 21, alpha=0.3, position = position_jitter(w = 0.20))
# Plotting the significant and the nonsignificant points differently
# size is proportional to relative abundance, and we colour it by Class
p = p + scale_size_continuous("log(Relative\nAbundance)",trans="log",guide="none")
# Transforming the size of the points so it's better visualized
p = p + facet_grid(~Genus, scales="free_x")
# Saying we want it to present the data separately for each phylum
p = p + geom_hline(yintercept = 1, linetype=2)
p = p + geom_hline(yintercept = -1, linetype=2)
p = p + geom_hline(yintercept = 3.3219, linetype=3)
p = p + geom_hline(yintercept = -3.3219, linetype=3)
p = p + geom_hline(yintercept = 0.0, linetype=1)
# Puts in horizontal lines at reference values
p = p + theme_bw()
p = p + theme(strip.text.x = element_text(size = 16),
              strip.text.y = element_text(size = 16),
              axis.text.x = element_text(size = 14, angle = 45, hjust = 1, vjust = 1, face="italic"),
              axis.title.x = element_text(size = 18),
              axis.text.y = element_text(size=16),
              axis.title.y = element_text(size = 18),
              legend.title = element_text(size=18),
              legend.text = element_text(size = 14),
              #legend.position = "none",
              strip.background = element_blank(),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank())
# sets a bunch of visual paramters for the legend (none) and other text
p = p + labs(y = expression(paste("", log[2]," fold change vs. Point site",sep="")))
# sets the label for the y axes
p
```
```{r plot_phylum_abundance}
mdf = psmelt(biom)
#"melting" the phyloseq data into a dataframe
# We want to calculate the total relative abundance of each phylum
# and then take the top X most abundant phyla
SortedPhyla = mdf %>%
  group_by(Sample,Phylum) %>%
  summarize(PhyAbund = sum(Abundance))%>%
  # Should give us the relative abundance of all OTUs in each phylum from each sample.
  group_by(Phylum)%>%
  summarize(MeanPhyAbund = mean(PhyAbund))%>%
  arrange(-MeanPhyAbund)
# Then sums the mean relative abundance of each phylum, across samples, and reports it from most to least
nPhyla = 13
# How many phyla do we want to include (plus 1 for NAs)?
PhylumList = SortedPhyla[1:nPhyla,1]
PhylumList = PhylumList[is.na(PhylumList)==FALSE,]
PhylumList = levels(droplevels(as.factor(PhylumList$Phylum)))
# List of nPhyla top most abundant phyla
PhylumList
biom2 = subset_taxa(biom, Phylum %in% PhylumList)
mdf2 = psmelt(biom2)
head(mdf2)
mdf2 = mdf2 %>%
  group_by(Sample,Site,Date,Phylum) %>%
  summarize(PhyAbund = sum(Abundance))
p = ggplot(mdf2, aes(Date, PhyAbund, fill = Date))
p = p + geom_boxplot()
p = p + facet_wrap(~Phylum, scales = "free_y")
#p = p + scale_fill_manual(values=c("orange","gold1","red3"))
p = p + theme_bw()
p = p + guides(fill = "none")
p = p + theme(legend.position = "none")
p = p + theme(strip.text.x = element_text(size=11), 
              strip.text.y = element_text(size=9), 
              strip.background = element_rect(colour="white", fill="white"))
p = p + theme(axis.text.x = element_text(size = 9, angle = 45, hjust=1),axis.text.y = element_text(size = 9))
p = p + theme(axis.title.x = element_blank())
p = p + theme(axis.title.y = element_text(size = 15, vjust = 1))
p = p + labs(x="Amendment",y="Relative abundance")
p
```
