---
title: "Using Phyloseq to Visualize QIIME Output from Cladophora Microbiota, 2014"
author: "Michael Braus"
date: "`r Sys.Date()`"
output: html_document
---
```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=9, fig.height=7, fig.path='QIIME2Phyloseq-figs/', warning=FALSE, message=FALSE, cache=TRUE)
```
```{r load_packages, results="hide"}
setwd("~/Dropbox/clado-manuscript/Mikes_MS_Data/")
library(ggplot2)
library(plyr)
library(dplyr)
library(Rmisc)
library(DESeq2)
library(doParallel)
#source('http://bioconductor.org/biocLite.R')
#biocLite('phyloseq')
library(phyloseq)
```
``` {r load_data, results="hide"}
# Load biom file. 
biom <- import_biom("OTU_table.biom", "~/Dropbox/clado-manuscript/Nephele/PipelineResults_NMEPINZ20QK1/nephele_outputs/tree.tre", parseFunction=parse_taxonomy_greengenes)
```
``` {r merge_metadata}
sam.data <- read.csv(file="sample.data.csv", row.names=1, header=TRUE)
head(sam.data)
sam.data$Date <- as.factor(sam.data$Date)
sam.data$DateSite <- paste(sam.data$Date, sam.data$Site)
head(sam.data); str(sam.data)
sample_data(biom) <- sam.data
biom; sample_data(biom)
head(otu_table(biom))
```
```{r ordination}
# Custom plotting. 
nolegend <- theme(legend.position="none")
readabund <- labs(y="read abundance")
# Normalize by relative abundance. 
biom.relabund <- transform_sample_counts(biom, function(x) x / sum(x))
# Ordination plot. 
ordNMDS <- ordinate(biom.relabund, method="NMDS", distance="bray")
ordNMDS.k3 <- ordinate(biom.relabund, method="NMDS", distance="bray", k=3)
ord.k3 <- plot_ordination(biom.relabund, ordNMDS.k3, shape="Site", color = "DateSite") + geom_point(size=3) + geom_polygon(aes(fill=DateSite), alpha=0.7)
ord.k3 + labs(title = "Cladophora, 2014") + theme_bw()
# Ordination plot in black and white. 
ord.k3.bw <- plot_ordination(biom.relabund, ordNMDS.k3, shape="Site", label = "Date") + geom_point(size=2) + geom_polygon(colour="black", size=0.25, fill="white", alpha = 0.2, aes(group=DateSite))
ord.k3.bw + labs(title = "Cladophora, 2014") + theme_bw()
# Facet by Date. 
ord.k3.facet1 <- plot_ordination(biom.relabund, ordNMDS.k3, shape="Site") + geom_point(size=2.5) + facet_wrap(~Date) + geom_polygon(colour="black", size=0.25, fill="white", alpha = 0.2, aes(group=DateSite))
ord.k3.facet1 + labs(title = "Cladophora, 2014") + theme_bw()
# Facet by Site. 
ord.k3.facet2 <- plot_ordination(biom.relabund, ordNMDS.k3, color = "Date") + geom_point(size=2.5) + facet_wrap(~Site, ncol = 1) + geom_polygon(colour="black", size=0.25, fill="white", alpha = 0.2, aes(group=DateSite))
ord.k3.facet2 + labs(title = "Cladophora, 2014") + theme_bw()
```
```{r methanos}
# Find methanotrophs
methanolist <- read.table(file = "methanos.txt")
methanolist <- as.vector(methanolist$V1)
# 
biom.relabund.methanos <- subset_taxa(biom.relabund, Genus %in% as.factor(methanolist))
biom.relabund.methanos
head(tax_table(biom.relabund.methanos))
# 
relabund.methanos <- psmelt(biom.relabund.methanos)
relabund.methanos.genus <- relabund.methanos%>%
  group_by(Sample, Genus)%>%
  mutate(GenusAbundance = sum(Abundance))%>%
  distinct(Sample, GenusAbundance, TreatmentGroup, Site, Date, Family, Genus)
head(relabund.methanos.genus)
# 
p <- ggplot(relabund.methanos.genus, aes(as.factor(Date), GenusAbundance, color = Site))
p <- p + geom_point() + facet_wrap(~Genus, scales="free_y")
p
# Stacked bar plots of methanotrophs. 
barstack.methanos <- plot_bar(biom.relabund.methanos, x = "Date", fill="Site") + facet_wrap(~Genus, scales="free_y")
barstack.methanos
```
```{r plot_relabund_methanos_summarySE, fig.width=9, fig.height=18}
relabund.methanos.genus.est <- summarySE(relabund.methanos.genus, measurevar="GenusAbundance", groupvars=c("Site","Date", "Genus"))
head(relabund.methanos.genus.est)
relabund.methanos.genus.est$Date <- as.character(relabund.methanos.genus.est$Date)
relabund.methanos.genus.est$Date <- as.numeric(relabund.methanos.genus.est$Date)
p <- ggplot(relabund.methanos.genus.est, aes(x=Date, y=GenusAbundance)) + geom_point() +  geom_errorbar(aes(ymin=GenusAbundance-se, ymax=GenusAbundance+se)) +  geom_smooth(method="lm", se=TRUE) + facet_wrap(~Genus~Site, ncol = 3, scales="free_y")
p + theme_bw() + theme(axis.text.x = element_text(size = 10, angle = 45, hjust=1),axis.text.y = element_text(size = 10))
```
```{r plot_richness_all}
# https://joey711.github.io/phyloseq/plot_richness-examples.html
# Plot richness. 
biom.rich <- plot_richness(biom, x="Date", color="Site", measures=c("Observed", "Chao1", "Shannon"))
biom.rich + geom_point(size=2, alpha=0.6)

biom.est.rich <- estimate_richness(biom, measures = NULL)
biom.est.rich$SampleID.1 <- row.names(biom.est.rich)
biom.est.rich <- merge(biom.est.rich, sam.data, by = "SampleID.1")
biom.est.rich$Date <- as.character(biom.est.rich$Date)
biom.est.rich$Date <- as.numeric(biom.est.rich$Date)
```
```{r plot_richness_obs}
biom.est.rich.obs <- summarySE(biom.est.rich, measurevar="Observed", groupvars=c("Date","Site"))
str(biom.est.rich.obs)
p.obs <- ggplot(biom.est.rich.obs, aes(x=Date, y=Observed)) + geom_point() +  geom_errorbar(aes(ymin=Observed-se, ymax=Observed+se)) + geom_smooth(method="lm",se=TRUE) + facet_grid(~ Site)
p.obs + theme_bw() + theme(axis.text.x = element_text(size = 10, angle = 45, hjust=1),axis.text.y = element_text(size = 10))
```
```{r plot_richness_sha}
biom.est.rich.sha <- summarySE(biom.est.rich, measurevar="Shannon", groupvars=c("Date","Site")); biom.est.rich.sha
p.sha <- ggplot(biom.est.rich.sha, aes(x=Date, y=Shannon)) + geom_point() +  geom_errorbar(aes(ymin=Shannon-se, ymax=Shannon+se)) +  geom_smooth(method="lm",se=TRUE) + facet_grid(~ Site)
p.sha + theme_bw() + theme(axis.text.x = element_text(size = 10, angle = 45, hjust=1),axis.text.y = element_text(size = 10))
```
```{r plot_richness_ch1}
biom.est.rich.ch1 <- summarySE(biom.est.rich, measurevar="Chao1", groupvars=c("Date","Site")); biom.est.rich.ch1
p.ch1 <- ggplot(biom.est.rich.ch1, aes(x=Date, y=Chao1)) + geom_point() +  geom_errorbar(aes(ymin=Chao1-se, ymax=Chao1+se)) +  geom_smooth(method="lm",se=TRUE) + facet_grid(~ Site)
p.ch1 + theme_bw() + theme(axis.text.x = element_text(size = 10, angle = 45, hjust=1),axis.text.y = element_text(size = 10))
```
```{r anosim}
library("vegan"); packageVersion("vegan")
# Anosim by site. 
site_group = get_variable(biom, "Site")
site_ano = anosim(phyloseq::distance(biom, "bray"), site_group)
site_ano
# Anosim by date. 
date_group = get_variable(biom, "Date")
date_ano = anosim(phyloseq::distance(biom, "bray"), date_group)
date_ano
# 
df = as(sample_data(biom), "data.frame")
d = phyloseq::distance(biom, "bray")
clado.adonis = adonis(d ~ Date + Site + Date*Site, df)
clado.adonis
```